### ISSUE TITLE
Highlighting tweaks

### ISSUE THREAD

**Issue by james2doyle** [bajrangCoder/zed-laravel-blade#1]
I made a PR to the Zed editor before extensions were added: https://github.com/zed-industries/zed/pull/6806/files.

I used https://github.com/EmranMR/tree-sitter-blade as a base.

![300099395-99aeb5bb-0c0c-47de-b6d1-18c43497880a](https://github.com/bajrangCoder/zed-laravel-blade/assets/1425304/33c86c52-cfa0-4fac-a766-b864900c2fd0)

I was able to get some decent highlighting out of it. Maybe you can incorporate some of the things I managed to get working in my PR. Thanks

**Comment by bajrangCoder** [comment]
This extension is also using the same tree-sitter grammar and this is also able to get initial highlighting but it can be improved and Sure I will definitely incorporate some of your tweaks and improvement with the coming `v0.0.2`

Thanks for your feedback ♥️
