### ISSUE TITLE
Guide to Use This Package

### ISSUE THREAD

**Issue by rizaldywirawan** [bajrangCoder/zed-laravel-blade#4]
Halo,

Thank you for the initiative to create package for Laravel Blade syntax highlight.

I tried to search a guide before create this issue about how to implement it, can you teach us how to do that?

Thank you

**Comment by bajrangCoder** [comment]
This is a extension for Zed code editor to provide language support of blade inside Zed. From Zed extension page(inside app) download it and open your blade file and select the language mode to blade.
